services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    buildCommand: cd my-todo-app/backend && npm install
    startCommand: cd my-todo-app/backend && node server.js
    envVars:
      - key: PORT
        value: 50000
      - key: MONGO_URI
        value: mongodb+srv://sneha1995sarkar25:O8QuvtugTTkhh8CE@cluster0.tomu2um.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  - type: web
    name: todo-frontend
    env: static
    buildCommand: cd my-todo-app/frontend && npm install && npm run build
    staticPublishPath: my-todo-app/frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://todo-backend.onrender.com
